---
labels:
  author: skipper@southwinds.io
  application: Pilot Control Service
  description: An HTTP API for managing Pilot agents

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: registry.gitlab.com/southwinds-pub/image
  APP_NAME: pilotctl
  # the application version
  APP_VERSION: 1.0.0
  # a unique build number
  BUILD_VERSION: ${APP_VERSION}-${ARTISAN_REF}

functions:
  - name: build-linux
    description: builds the PilotCtl binary file for the linux platform
    env:
      GOOS: linux
    run:
      - go fmt
      - go build -ldflags="-w -s -X 'southwinds.dev/piloctl/core.Version=${BUILD_VERSION}'" -o bin/pilotctl -v

  - name: swagen
    description: generates/refreshes the OpenAPI specifications for PilotCtl's HTTP API
    run:
      - swag init -d "./,types,../artisan/data" -g handlers.go

  - name: release
    description: builds and publishes the Pilot Control image
    run:
      - $(build-linux)
      - cp bin/pilotctl build/
      - docker pull registry.access.redhat.com/ubi8/ubi-minimal
      - docker build -t ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} build
      - docker tag ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} ${REPO_NAME}/${APP_NAME}:latest
      - docker push ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION}
      - docker push ${REPO_NAME}/${APP_NAME}:latest

  - name: build-image-local
    description: builds and publishes the Pilot Control image
    run:
      - $(build-linux)
      - cp bin/pilotctl build/
      - docker build -t ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} build
      - docker tag ${REPO_NAME}/${APP_NAME}:${BUILD_VERSION} ${REPO_NAME}/${APP_NAME}:latest

  - name: up
    run:
      - docker run --name rem -d -p 8080:8080 ${REPO_NAME}/${APP_NAME}
...
